export * from "./listsActions"

export const CONSTANTS = {
  LIST_SEARCHED: "LIST_SEARCHED",
  ADD_LIST: "ADD_LIST",
  REMOVE: "REMOVE",
  UPDATE: "UPDATE",
  ADD_ERR: "ADD_ERR",
  REMOVE_ERR: "REMOVE_ERR",
  UPDATE_ERR: "UPDATE_ERR"
}

